import Head from 'next/head';
import { useAppBridge } from '@/hooks';
import UserInfo from '../../components/UserInfo';

type User = {
	id: number;
	friendly_name: string;
};

type UserInfo = {
	user: User;
};

export default function Home() {
	const { completed } = useAppBridge({ type: 'space-plugin', oauth: true });

	return (
		<>
			<Head>
				<title>Storyblok Next Tool Starter</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main>
				{completed && (
					<div>
						<p>Authenticated!</p>
						<UserInfo />
					</div>
				)}
			</main>
		</>
	);
}
