name: 'ci-next-templates'
on:
  push:
    paths:
      - 'space-plugins/nextjs-starter/**'
      - 'tool-plugins/nextjs-starter/**'
  pull_request:
    paths:
      - 'space-plugins/nextjs-starter/**'
      - 'tool-plugins/nextjs-starter/**'
jobs:
  nextjs-space-plugin-starter-checks:
    runs-on: ubuntu-latest
    name: Build Next Space Plugin Starter
    defaults:
      run:
        working-directory: ./space-plugins/nextjs-starter
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Build Space Plugin Starter
        run: pnpm build
  nextjs-tool-plugin-starter-checks:
    runs-on: ubuntu-latest
    name: Build Next Tool Plugin Starter
    defaults:
      run:
        working-directory: ./tool-plugins/nextjs-starter
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build Tool Plugin Starter
        run: yarn build
