name: 'ci-story'
on:
  push:
    paths:
      - 'story-starter/**'
jobs:
  story-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - run: |
          cd story-starter
          pnpm install
          pnpm -F nuxt run lint
          pnpm -F nuxt run build
